# Makefile for CCITT subroutines and sample programs
#

# Modify the CC definition to invoke your ANSI-C compiler
#

#############################
# Modified by C. Lee
#CC =  ../../../bin/ssbig-na-sstrix-gcc # gcc -mv8 -static
CC= /home/lqingrui/idriver/gcc.sh

#static compilation
IDEMFLAG = --idempotence-construction=none --idempotence-preservation=none --livein-checkpoint=none --reverse-compute=none --target=armv7 -funroll-loops -static
CFLAGS = -O3 $(IDEMFLAG) -static
LDFLAGS= -O3 -static --target=armv7

##dynamic compilation
#IDEMFLAG = --idempotence-construction=none --idempotence-preservation=none --livein-checkpoint=none --reverse-compute=none --target=armv7 -funroll-loops
#CFLAGS = -O3 $(IDEMFLAG)
#LDFLAGS= -O3 --target=armv7

LN= /home/lqingrui/gcc/gcc-arm-build/bin/arm-none-linux-gnueabi-gcc

#CC=gcc
#CFLAGS=-O3 -static
#LN=gcc
#LDFLAGS= -O3 -static
# Rules to build sample programs do not depend on a UNIX library program
#
ALL = encode decode
all: $(ALL)
	cp encode decode ../bin/.


OBJECTS = g711.o g72x.o g721.o g723_24.o g723_40.o

#encode: $(OBJECTS) encode.c
#	$(CC) -o $@ encode.c $(OBJECTS)
#
#decode: $(OBJECTS) decode.c
#	$(CC) -o $@ decode.c $(OBJECTS)

encode:  $(OBJECTS) encode.o
	$(LN) $(LDFLAGS) -o $@ $(OBJECTS) encode.o

decode:  $(OBJECTS) decode.o
	$(LN) $(LDFLAGS) -o $@ $(OBJECTS) decode.o

# Library rules for UNIX systems
#
LIB = ccitt.a
lib: $(LIB)

%.o: %.c
	$(CC) $(CFLAGS) $<

#$(LIB): $(OBJECTS)
#	@rm -f $(LIB)
#	ar cr $(LIB) $(OBJECTS)
#	@ranlib $(LIB)

clean:
	/bin/rm -f $(LIB) $(ALL) *.o *.ll *.s *.bc ; /bin/rm -f ../bin/*
