echo "accum.i"

/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option accum.i 

echo "alpha.i"

/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option alpha.i 

echo "alphabuf.i"
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option alphabuf.i 

echo "api.i"
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option api.i
echo "attrib.i"

/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option attrib.i 
echo "bitmap.i"
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option bitmap.i 
echo "blend.i"
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option blend.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option bresenhm.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option clip.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option context.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option copypix.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option depth.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option dlist.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option draw.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option drawpix.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option enable.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option eval.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option feedback.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option fog.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option get.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option interp.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option image.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option light.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option lines.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option logic.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option masking.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option matrix.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option misc.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option pb.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option pixel.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option points.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option pointers.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option polygon.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option readpix.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option scissor.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option span.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option stencil.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option teximage.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option texobj.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option texture.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option triangle.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option varray.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option vb.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option vertex.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option winpos.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option xform.i 
/home/xlous/Development/compiler/llvm-idem/llvm/cmake-build-debug/bin/clang -cc1 -I../include -DSHM  -mllvm -enable-reg-renaming-idem=true -mllvm -renaming-idem-verify -O3 -triple armv7-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -ferror-limit 19 -fmessage-length 204 -fdiagnostics-show-option osmesa.i


